### ISSUE TITLE
Question: Where did you learn how to reprogram the LCD?

### ISSUE THREAD

**Issue by justinbarclay** [IsSuEat/zoom75-lcd-tool#1]
Hey, 

I'm looking at doing something similar to this project, but I am wondering if you know of a place to find docs for this LCD or more generally what sort of investigating you did to figure out it's interface?

**Comment by IsSuEat** [comment]
Hi. Sadly the LCD is not documented anywhere (at least I couldn't find anything). I took a look at what the windows and mac tools for the keyboard do  :)

**Comment by justinbarclay** [comment]
Yeah, that's what I assumed. Thanks for the info :)
